### ISSUE TITLE
Self-hosted environment: "Register Local Environment Failure: vso login failed: System.TimeoutException"

### ISSUE THREAD

**Issue by rold2007** [MicrosoftDocs/vsonline#297]
I get an issue similar to #235 and #255 but with a different cause.

It looks like I hit a timeout:
[2020-01-30 11:18:14.563 Command:u E] Command [Register Local Environment]: **Register Local Environment Failure: vso login failed: System.TimeoutException: RPC connection timed out**, Timeout:00:00:02. Make sure the **VSLS agent** process is running.
   at Microsoft.Cascade.Client.CascadeClient.CreateWithTimeoutAsync(IRpcClient rpcClient, TimeSpan timeout, TraceSource trace, CancellationToken cancellationToken) in E:\A\_work\55\s\src\Client\CascadeClient.cs:line 147
   at Microsoft.VisualStudio.VSOnline.Core.CascadeFactory.CreateClientAsync(Boolean autoStart) in E:\A\_work\55\s\src\VSOnline\Core\CascadeFactory.cs:line 62
   at Microsoft.VisualStudio.VSOnline.Core.Managers.AuthenticationManager.LoginExchangeAsync(String aadToken) in E:\A\_work\55\s\src\VSOnline\Core\Managers\AuthenticationManager.cs:line 39
   at Microsoft.CloudEnvironments.CLI.Commands.LoginAuthenticationCliCommandStrategy.LoginExchangeAsync(String aadToken) in E:\A\_work\55\s\src\VSOnline\CLI\Commands\LoginAuthenticationCliCommandStrategy.cs:line 55
   at Microsoft.CloudEnvironments.CLI.Commands.LoginAuthenticationCliCommandStrategy.<>c__DisplayClass4_2.<<Register>b__3>d.MoveNext() in E:\A\_work\55\s\src\VSOnline\CLI\Commands\LoginAuthenticationCliCommandStrategy.cs:line 40
 **(195061ms)**

Note that this is running on a very low-end hardware, which could explain the 195061ms.
Also, I'm wondering how I am supposed to "**Make sure** the VSLS agent process is running.". Which process is it ?

**Comment by taiyosogawa** [comment]
Sorry for the very late reply!

Thanks for reporting this issue, and good question about the VSLS agent. I can see how it's unclear how to act on that message.

We have recently changed the relevant timeout configurations and I think it will likely resolve this issue. The change will be rolled out soon, and I'll post here when it's available.

**Comment by rold2007** [comment]
Thanks for the update. I'll wait for your post before I try it again.

**Comment by justusgametv** [comment]
Yea same issue for me.

**Comment by justusgametv** [comment]
Not sure it will help but I change the name from the default, which was the PC name and it contained "-" (dashes) and it worked for me.

**Comment by rold2007** [comment]
@justusgametv I have no dash in my PC name and I tried with different names, but it never worked. So I guess the dash problem is a different issue.

**Comment by taiyosogawa** [comment]
@rold2007, we've deployed the update that I think might resolve this issue. Could you give it another try? No extension update required.

**Comment by rold2007** [comment]
@taiyosogawa I tried again, but this time I have a different timeout error...

[2020-02-27 01:18:00.278 Client I] User logged in as ----------------
[2020-02-27 01:18:34.592 Command:u I] Decorator starting: l
[2020-02-27 01:18:34.594 Command:u I] Decorator starting: a
[2020-02-27 01:19:26.024 Command:u E] Command [Register Local Environment]: Register Local Environment Failure: vso share timeout exceeded (30000 ms) (51421ms)
[2020-02-27 01:19:26.032 Command:u I] Decorator finishing: a. Duration: 104ms (2 + 102)
[2020-02-27 01:23:30.052 Command:p I] Decorator starting: l
[2020-02-27 01:23:30.053 Command:p I] Decorator starting: a

**Comment by taiyosogawa** [comment]
@rold2007, apologies for the difficulties - self-hosted environment registration has been facing higher-than-normal issues this last week. We will be rolling out some more important updates soon, so I might just wait for those, but here are some things you can do to help reset/diagnose.

1) Delete the 'vso' folder in your temp directory if present.
2) If you're using Windows, go to your credential manager (Windows Credentials) and delete anything that starts with 'Microsoft_VS_Liveshare/' (there should be around 5)
3) When you run register, monitor the processes running on your machine. Do you see a new instance of 'vsls-agent' running out of the '%TEMP%/vso' directory? If you do, does it die or does it appear long-lived?

**Comment by rold2007** [comment]
@taiyosogawa I tried to delete all files/folders in vso but one of them was locked even if VSCode was closed. I had to kill the remaining agent process to be able to delete everything.
After deleting the credentials I tried to register again but it still didn't work. The vsls-agent process was still running, so it seems long-lived.

I'll try again after the next updates.

**Comment by taiyosogawa** [comment]
Ah, I'm sorry that didn't work for you.

As a quick update: the new updates have been partially rolled out, so you may or may not see them right now. It should be fully complete in the next couple days. When it is available for you, you should see this folder under "%TEMP%\vso" after you try to register again: VSOAgent_win_3495655. Based on your logs, I am pretty sure it will fix this issue.

**Comment by taiyosogawa** [comment]
Hi @rold2007, we were able to fully deploy the updates - try giving it another shot and let me know if it works. Other customers have reported that they've needed to kill all instances of "vsls-agent" processes and restart their machines before it worked. However, it does not require an extension update.

**Comment by rold2007** [comment]
I did a reboot before testing, just in case.
When I ran the registration I had a version different from the one you said I would have: VSOAgent_win_3512918
Is this version also ok ?

The registration didn't work, and I had the same message as last time in the log.

Command:u E] Command [Register Local Environment]: Register Local Environment Failure: vso share timeout exceeded (30000 ms) (274847ms)

Is there any way for me to increase this 30000ms timeout ?

**Comment by rold2007** [comment]
I tried again yesterday just in case, and this time it worked !

I had this in my log file:
Command [Register Self-hosted Environment]: Register Self-hosted Environment Success (32123ms)

So I guess that the solution is to try many times until it takes less than 30s...

**Comment by taiyosogawa** [comment]
Sorry I didn't reply to your previous message and so glad it worked in the end! We're working to make self-hosted environments more stable, so we really appreciate that you reached out and worked with us.
