### ISSUE TITLE
Renderer Process consuming high percentage of CPU

### ISSUE THREAD

**Issue by kieferrm** [MicrosoftDocs/vsonline#338]
Chrome Version 80.0.3987.132 (Official Build) (64-bit) on macOS

1) create a new environment on `online.visualstudio.com/environments` using `https://github.com/joshaber/simple-server`
2) create standard environment 
3) open environment  in the web UI
=> within a few seconds Chrome runs on 170% CPU

This does not happen when running from source or using the prebuilt web UI in other remote contexts.

It does not happen all the time but in most cases (8/10). When it happens I see the following errors in the dev tools log:

```
workbench.web.api.js:sourcemap:1535   ERR Handler already set!: Error: Handler already set!
    at u.setHandler (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:3257:409)
    at g.initialize (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:4771:645)
    at new g (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:4771:617)
    at new B (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:4773:935)
    at h._createInstance (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1521:381)
    at h._createServiceInstance (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1523:458)
    at h._createServiceInstanceWithOwner (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1522:930)
    at h._createAndCacheServiceInstance (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1522:605)
    at h._getOrCreateServiceInstance (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1521:889)
    at Object.get (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1520:388)
workbench.web.api.js:sourcemap:3257 Uncaught Error: Handler already set!
    at u.setHandler (workbench.web.api.js:sourcemap:3257)
    at g.initialize (workbench.web.api.js:sourcemap:4771)
    at new g (workbench.web.api.js:sourcemap:4771)
    at new B (workbench.web.api.js:sourcemap:4773)
    at h._createInstance (workbench.web.api.js:sourcemap:1521)
    at h._createServiceInstance (workbench.web.api.js:sourcemap:1523)
    at h._createServiceInstanceWithOwner (workbench.web.api.js:sourcemap:1522)
    at h._createAndCacheServiceInstance (workbench.web.api.js:sourcemap:1522)
    at h._getOrCreateServiceInstance (workbench.web.api.js:sourcemap:1521)
    at h._createInstance (workbench.web.api.js:sourcemap:1520)
workbench.web.api.js:sourcemap:1535   ERR Unable to write file 'vscode-log:/20200309T142348/window.log' (EntryNotADirectory (FileSystemError): vscode-log:/20200309T142348/window.log): Error: Unable to write file 'vscode-log:/20200309T142348/window.log' (EntryNotADirectory (FileSystemError): vscode-log:/20200309T142348/window.log)
    at _.writeFile (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1552:834)
workbench.web.api.js:sourcemap:1535   ERR Handler already set!: Error: Handler already set!
    at u.setHandler (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:3257:409)
    at g.initialize (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:4771:645)
    at new g (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:4771:617)
    at new B (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:4773:935)
    at h._createInstance (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1521:381)
    at h._createServiceInstance (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1523:458)
    at h._createServiceInstanceWithOwner (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1522:930)
    at h._createAndCacheServiceInstance (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1522:605)
    at h._getOrCreateServiceInstance (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1521:889)
    at h._createInstance (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1520:918)
extensionHostWorkerMain.js:1 Uncaught (in promise) Error: Unknown actor MainThreadWindow
    at g._doInvokeHandler (workbench.web.api.js:3502)
    at g._invokeHandler (workbench.web.api.js:3502)
    at g._receiveRequest (workbench.web.api.js:3500)
    at g._receiveOneMessage (workbench.web.api.js:3499)
    at workbench.web.api.js:3497
    at c.fire (workbench.web.api.js:116)
    at Worker.l.onmessage (workbench.web.api.js:3734)
workbench.web.api.js:sourcemap:1535   ERR Unable to write file 'vscode-log:/20200309T142348/window.log' (EntryNotADirectory (FileSystemError): vscode-log:/20200309T142348/window.log): Error: Unable to write file 'vscode-log:/20200309T142348/window.log' (EntryNotADirectory (FileSystemError): vscode-log:/20200309T142348/window.log)
    at _.writeFile (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1552:834)
workbench.web.api.js:sourcemap:1535   ERR Handler already set!: Error: Handler already set!
    at u.setHandler (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:3257:409)
    at g.initialize (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:4771:645)
    at new g (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:4771:617)
    at new B (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:4773:935)
    at h._createInstance (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1521:381)
    at h._createServiceInstance (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1523:458)
    at h._createServiceInstanceWithOwner (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1522:930)
    at h._createAndCacheServiceInstance (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1522:605)
    at h._getOrCreateServiceInstance (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1521:889)
    at h._createInstance (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1520:918)
workbench.web.api.js:sourcemap:1535   ERR Unable to write file 'vscode-log:/20200309T142348/window.log' (EntryNotADirectory (FileSystemError): vscode-log:/20200309T142348/window.log): Error: Unable to write file 'vscode-log:/20200309T142348/window.log' (EntryNotADirectory (FileSystemError): vscode-log:/20200309T142348/window.log)
    at _.writeFile (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:1552:834)
workbench.web.api.js:sourcemap:5754 Uncaught TypeError: Cannot read property 'layout' of undefined
    at V.layout (workbench.web.api.js:sourcemap:5754)
    at workbench.web.api.js:sourcemap:5770
DevTools failed to parse SourceMap: https://ticino.blob.core.windows.net/sourcemaps/c47d83b293181d9be64f27ff093689e8e7aed054/core/vs/workbench/workbench.web.api.nls.js.map
DevTools failed to parse SourceMap: https://ticino.blob.core.windows.net/sourcemaps/c47d83b293181d9be64f27ff093689e8e7aed054/core/vs/workbench/services/keybinding/browser/keyboardLayouts/layout.contribution.darwin.js.map
DevTools failed to parse SourceMap: https://ticino.blob.core.windows.net/sourcemaps/c47d83b293181d9be64f27ff093689e8e7aed054/core/vs/workbench/services/extensions/worker/extensionHostWorkerMain.js.map
2DevTools failed to parse SourceMap: https://ticino.blob.core.windows.net/sourcemaps/c47d83b293181d9be64f27ff093689e8e7aed054/core/vs/workbench/services/extensions/worker/extensionHostWorker.js.map
DevTools failed to parse SourceMap: https://ticino.blob.core.windows.net/sourcemaps/c47d83b293181d9be64f27ff093689e8e7aed054/core/vs/workbench/services/extensions/worker/extensionHostWorker.nls.js.map
```

**Comment by praksb** [comment]
I am running into the same issue as well.

**Comment by kieferrm** [comment]
I realize that this only happens when the environment is `available` and not when it is `suspended`.

Here is what I see in newly resumed environment:
```
[2020-03-09 22:36:48.134] [remoteagent] [info] Extension host agent started.
[2020-03-09 22:36:49.493] [remoteagent] [info] [::ffff:127.0.0.1][a5b571fa][ManagementConnection] New connection established.
[2020-03-09 22:36:49.512] [remoteagent] [info] [::ffff:127.0.0.1][d71aedc9][ExtensionHostConnection] New connection established.
[2020-03-09 22:36:49.916] [remoteagent] [info] [::ffff:127.0.0.1][d71aedc9][ExtensionHostConnection] <272> Launched Extension Host Process.
```

If I then go back to the dashboard to back into the already running environment:
```
[2020-03-09 22:36:48.134] [remoteagent] [info] Extension host agent started.
[2020-03-09 22:36:49.493] [remoteagent] [info] [::ffff:127.0.0.1][a5b571fa][ManagementConnection] New connection established.
[2020-03-09 22:36:49.512] [remoteagent] [info] [::ffff:127.0.0.1][d71aedc9][ExtensionHostConnection] New connection established.
[2020-03-09 22:36:49.916] [remoteagent] [info] [::ffff:127.0.0.1][d71aedc9][ExtensionHostConnection] <272> Launched Extension Host Process.
[2020-03-09 22:37:30.123] [remoteagent] [info] [::ffff:127.0.0.1][a5b571fa][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2020-03-09 22:37:31.123] [remoteagent] [info] [::ffff:127.0.0.1][d71aedc9][ExtensionHostConnection] <272> Extension Host Process exited with code: 0, signal: null.
[2020-03-09 22:37:31.123] [remoteagent] [info] Last EH closed, waiting before shutting down
[2020-03-09 22:37:44.031] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2020-03-09 22:37:44.031] [remoteagent] [info] Cancelling previous shutdown timeout
[2020-03-09 22:37:44.857] [remoteagent] [info] [::ffff:127.0.0.1][bc60bbf2][ManagementConnection] New connection established.
[2020-03-09 22:37:44.874] [remoteagent] [info] [::ffff:127.0.0.1][c3bd7624][ExtensionHostConnection] New connection established.
[2020-03-09 22:37:44.875] [remoteagent] [info] [::ffff:127.0.0.1][1fa703c8][ManagementConnection] New connection established.
[2020-03-09 22:37:44.875] [remoteagent] [info] [::ffff:127.0.0.1][e4978e3c][ExtensionHostConnection] New connection established.
[2020-03-09 22:37:44.878] [remoteagent] [info] [::ffff:127.0.0.1][c3bd7624][ExtensionHostConnection] <372> Launched Extension Host Process.
[2020-03-09 22:37:44.880] [remoteagent] [info] [::ffff:127.0.0.1][e4978e3c][ExtensionHostConnection] <373> Launched Extension Host Process.
```

What is suspicious here is that two extension host process are being  launched.

**Comment by kieferrm** [comment]
@jkeech has also observed that there are many instances of
```
$onUnexpectedError:
[{
    "$isError": true,
    "name": "Error",
    "message": "Unknown actor MainThreadErrors",
    "stack": "Error: Unknown actor MainThreadErrors    at g._doInvokeHandler (https://online.dev.core.vsengsaas.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:3502:233)
    at g._invokeHandler (https://online.dev.core.vsengsaas.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:3502:113)
    at g._receiveRequest (https://online.dev.core.vsengsaas.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:3500:772)
    at g._receiveOneMessage (https://online.dev.core.vsengsaas.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:3499:603)
    at https://online.dev.core.vsengsaas.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:3497:821
    at c.fire (https://online.dev.core.vsengsaas.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:116:845)
    at v.fire (https://online.dev.core.vsengsaas.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:365:97)
    at t.PersistentProtocol._receiveMessage (https://online.dev.core.vsengsaas.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:369:451)
    at https://online.dev.core.vsengsaas.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:366:635
    at c.fire (https://online.dev.core.vsengsaas.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:116:845)"
}] +20ms```

**Comment by bpasero** [comment]
It looks like the workbench is being created twice which is **NOT** supported right now. I will push a change on our end to throw an error if you try to instantiate the workbench twice to prevent this from happening in the future and we can have a separate discussion why this is needed and see if we have to support it this way or another way. The workbench is NOT ready to be disposed and recreated without context switch (e.g. window reload) due to a ton of static registries that we have. We never had the need for this scenario for VSCode desktop, so it would be new code to write and probably not have a lot of coverage in selfhosting.

Proof:

![Kapture 2020-03-10 at 7 40 00](https://user-images.githubusercontent.com/900690/76286429-724b8f80-62a2-11ea-8cba-686420dc8a4e.gif)

**Comment by legomushroom** [comment]
cc @plisy @osortega

**Comment by osortega** [comment]
The fix is done and released already.
Thanks for reporting!
