### ISSUE TITLE
Unable to create local environment

### ISSUE THREAD

**Issue by jaydeboer** [MicrosoftDocs/vsonline#367]
Each time I try to create a local environment if fails with `Register Self-hosted Environment: Sharing environment failed.`  If I then go look at my environments at online.visualstudio.com/environments it shows as 'Creating' and it doesn't ever seem to complete.  I've deleted the /$TMPDIR/vso folder.

**The logs from the extension are:**
```
[Client I] User logged in as *********@gmail.com
[AuthenticationInit I] User logged in as ********@gmail.com
[EnvironmentDetailsExplorer I] Updating environment details
[Command:u I] Decorator starting: l
[Command:u I] Decorator starting: a
[EnvironmentDetailsExplorer I] Updating environment details
[Command:u E] Command [Register Self-hosted Environment]: Register Self-hosted Environment Failure: vso login failed: Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.VisualStudio.VSOnline.Core.BaseClasses.FilePathProviderBase.get_VsoBaseFolder() in E:\A\_work\422\s\src\VSOnline\Core\BaseClasses\FilePathProviderBase.cs:line 51
   at Microsoft.VisualStudio.VSOnline.Core.BaseClasses.FilePathProviderBase.get_VsoSharedFolder() in E:\A\_work\422\s\src\VSOnline\Core\BaseClasses\FilePathProviderBase.cs:line 66
   at Microsoft.VisualStudio.VSOnline.Core.BaseClasses.FilePathProviderBase.get_EnvironmentVariablesFilePath() in E:\A\_work\422\s\src\VSOnline\Core\BaseClasses\FilePathProviderBase.cs:line 193
   at Microsoft.VisualStudio.VSOnline.Core.Providers.CloudEnvironmentFileInputProvider.Refresh() in E:\A\_work\422\s\src\VSOnline\Core\Providers\CloudEnvironmentFileInputProvider.cs:line 50
   at Microsoft.VisualStudio.VSOnline.Core.Providers.CloudEnvironmentFileInputProvider..ctor(FilePathProviderBase fileProvider, TraceSource trace) in E:\A\_work\422\s\src\VSOnline\Core\Providers\CloudEnvironmentFileInputProvider.cs:line 26
   at Microsoft.CloudEnvironments.CLI.Program.RegisterCommands(TraceSource trace, TraceSource allTrace, IConfigurationRoot config) in E:\A\_work\422\s\src\VSOnline\CLI\Program.cs:line 182
   at Microsoft.CloudEnvironments.CLI.Program.Main(String[] args) in E:\A\_work\422\s\src\VSOnline\CLI\Program.cs:line 102
 (20938ms)
[Command:u I] Decorator finishing: a. Duration: 5ms (0 + 5)
[EnvironmentDetailsExplorer I] Updating environment details
[EnvironmentDetailsExplorer I] Updating environment details
[Command:u I] Decorator finishing: l. Duration: 16804ms (0 + 16804)
```

After digging around some more

**VSCode Details:**
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Visual Studio Online Version:** 1.0.1889

**Comment by taiyosogawa** [comment]
@jaydeboer thank you very much for reporting this - the detailed information is very helpful.

We put in a fix for this and will be rolling it out in our next deployment. I'll update this thread when it becomes available.

**Comment by prokyon** [comment]
Same problem here (version 1.43.2, OS: Darwin x64 19.3.0) `Register Self-hosted Environment: Sharing environment failed.`. _Creating_ is also displayed at online.visualstudio.com/environments, but there is no further update.

I have also created a new plan (WestEurope) - also without success.

**VSCode:**
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Log export:**
````
[Client I] User logged in as ****.****@******-**.de
[Client I] Extension activating {"isInternal":false,"isRunningInCloudEnvironment":false,"serviceEndpoint":"https://online.visualstudio.com/api/v1/environments"}
[EnvironmentDetailsExplorer I] Updating environment details
[EnvironmentDetailsExplorer I] Updating environment details
[EnvironmentDetailsExplorer I] Updating environment details
[Command:p I] Decorator starting: l
[Command:p I] Decorator starting: a
[Command:p E] Command [Create New Environment]: Create New Environment Failure:  (7222ms)
[Command:p I] Decorator finishing: a. Duration: 11ms (0 + 11)
[Command:p I] Decorator finishing: l. Duration: 1ms (1 + 0)
[Command:u I] Decorator starting: l
[Command:u I] Decorator starting: a
[EnvironmentDetailsExplorer I] Updating environment details
[EnvironmentDetailsExplorer I] Updating environment details
[Command:u E] Command [Register Self-hosted Environment]: Register Self-hosted Environment Failure: vso login failed: Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.VisualStudio.VSOnline.Core.BaseClasses.FilePathProviderBase.get_VsoBaseFolder() in E:\A\_work\422\s\src\VSOnline\Core\BaseClasses\FilePathProviderBase.cs:line 51
   at Microsoft.VisualStudio.VSOnline.Core.BaseClasses.FilePathProviderBase.get_VsoSharedFolder() in E:\A\_work\422\s\src\VSOnline\Core\BaseClasses\FilePathProviderBase.cs:line 66
   at Microsoft.VisualStudio.VSOnline.Core.BaseClasses.FilePathProviderBase.get_EnvironmentVariablesFilePath() in E:\A\_work\422\s\src\VSOnline\Core\BaseClasses\FilePathProviderBase.cs:line 193
   at Microsoft.VisualStudio.VSOnline.Core.Providers.CloudEnvironmentFileInputProvider.Refresh() in E:\A\_work\422\s\src\VSOnline\Core\Providers\CloudEnvironmentFileInputProvider.cs:line 50
   at Microsoft.VisualStudio.VSOnline.Core.Providers.CloudEnvironmentFileInputProvider..ctor(FilePathProviderBase fileProvider, TraceSource trace) in E:\A\_work\422\s\src\VSOnline\Core\Providers\CloudEnvironmentFileInputProvider.cs:line 26
   at Microsoft.CloudEnvironments.CLI.Program.RegisterCommands(TraceSource trace, TraceSource allTrace, IConfigurationRoot config) in E:\A\_work\422\s\src\VSOnline\CLI\Program.cs:line 182
   at Microsoft.CloudEnvironments.CLI.Program.Main(String[] args) in E:\A\_work\422\s\src\VSOnline\CLI\Program.cs:line 102
 (90560ms)
[Command:u I] Decorator finishing: a. Duration: 12ms (0 + 12)
[EnvironmentDetailsExplorer I] Updating environment details
[...]
[EnvironmentDetailsExplorer I] Updating environment details
[Command:p I] Decorator starting: l
[Command:p I] Decorator starting: a
[EnvironmentDetailsExplorer I] Updating environment details
````

**Comment by taiyosogawa** [comment]
@prokyon, I apologize for the poor experience. This is affecting all OSX self-hosted environments and the update will be available early next week. No extension update will be required.

We understand that we've missed the mark here and as a result, we're dedicating resources to improving QA for self-hosted environments. Thanks for using self-hosted, and I'll update when the fix has been deployed.

**Comment by jaydeboer** [comment]
@taiyosogawa Thanks so much for the quick response!  As a developer, I certainly understand that bugs can sneak in.  Keep up all the good work you guys are doing!

**Comment by LimpingNinja** [comment]
I just came here specifically for @prokyon's error - OSX/Darwin and Path cannot be null. Glad to see it has already been diagnosed and rolling out. Hopefully we see it in West Europe soon!

**Comment by taiyosogawa** [comment]
Hi all - thanks again for connecting with us. The fix for this issue has deployed worldwide, so please give it another try!
