### ISSUE TITLE
vso info reads NOTICE.md from wrong directory

### ISSUE THREAD

**Issue by jaredpar** [MicrosoftDocs/vsonline#407]
Acquired the vso tools following the instructions on [this blog post](https://devblogs.microsoft.com/visualstudio/bring-your-own-machine-to-visual-studio-online/). After doing so I ran `vso info` to work through a different issue and this caused an unhandled exception to occur. 

Based on the exception it appears that the tool is attempting to read `NOTICE.md` from the current working directory where it should be looking in the application directory. Changing my directory to `c:\VSOnline` fixed the issue. 

```cmd
C:\WINDOWS\system32>c:\VSOnline\vso info
[2020-04-15 15:04:17.203 CLI I] vso v1.0.2005.59801 (pid: 15280)
[CLI E] Exception: System.IO.FileNotFoundException: Could not find file 'C:\WINDOWS\system32\NOTICE.md'.
File name: 'C:\WINDOWS\system32\NOTICE.md'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.CloudEnvironments.CLI.Commands.InfoCommandStrategy.<>c.<Register>b__1_1() in E:\A\_work\459\s\src\VSOnline\CLI\Commands\InfoCommandStrategy.cs:line 20
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.CloudEnvironments.CLI.Program.Main(String[] args) in E:\A\_work\459\s\src\VSOnline\CLI\Program.cs:line 148
System.IO.FileNotFoundException: Could not find file 'C:\WINDOWS\system32\NOTICE.md'.
File name: 'C:\WINDOWS\system32\NOTICE.md'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.CloudEnvironments.CLI.Commands.InfoCommandStrategy.<>c.<Register>b__1_1() in E:\A\_work\459\s\src\VSOnline\CLI\Commands\InfoCommandStrategy.cs:line 20
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.CloudEnvironments.CLI.Program.Main(String[] args) in E:\A\_work\459\s\src\VSOnline\CLI\Program.cs:line 148
```

**Comment by stuartleeks** [comment]
Same here on Ubuntu (changing to `/opt/vsonline/bin/` succeeds)

**Comment by taiyosogawa** [comment]
Thanks! It has been corrected and will probably be available next week.

**Comment by stuartleeks** [comment]
Cool, thanks!

**Comment by taiyosogawa** [comment]
Forgot to close this out, but the fix has been deployed. Thanks again for calling it out :)

**Comment by jaredpar** [comment]
@taiyosogawa what is the best way to get new drops of the tools? Is the expectation that I download a new drop manually or will the drop auto-update?

**Comment by zmetcalf** [comment]
@taiyosogawa is there a way to bump the linux (debian 10) repository so we can have access to this fix. My version is still matching the problem one.
