### ISSUE TITLE
Unable to connect to self-hosted environment: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by fpintos** [MicrosoftDocs/vsonline#421]
I'm unable to connect to a self-hosted environment, both with local vscode and from the web version in https://online.visualstudio.com/environments.

Both report the following error:
Failed to connect to the remote extension host server (Error: Object reference not set to an instance of an object.)

Exporting the logs from the local vscode I found this mentioned in the logs:
[2020-04-21 04:33:13.564 IVSCodeServerHostService V] < IVSCodeServerHostService.startRemoteServer()
[2020-04-21 04:33:13.813 IVSCodeServerHostService E] > IVSCodeServerHostService.startRemoteServer() error: undefined

In the hosting machine, the logs produced by vsonline:export didn't seem to have anything in particular.

**Comment by fpintos** [comment]
Found this in the hosting machine logs:

```
[2020-04-21 06:08:40.875 Command:l E] Command [Restore Self-hosted Environment]: Restore Self-hosted Environment Failure: vso share failed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Cascade.Agent.WorkspaceService.ShareWorkspaceAsync(WorkspaceShareInfo shareInfo, CancellationToken cancellationToken) in E:\A\_work\403\s\src\Agent\WorkspaceService.cs:line 346
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.<>c__DisplayClass24_2.<<CreateDispatchMethod>b__4>d.MoveNext() in E:\A\_work\403\s\src\Rpc\RpcDispatcher.cs:line 309
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.HandleRequestAsync(RequestMessage request, IProgress`1 progress, CancellationToken cancellationToken) in E:\A\_work\403\s\src\Rpc\RpcDispatcher.cs:line 102
   at Microsoft.Cascade.Rpc.RpcSession.RequestAsync(IRpcService service, RequestMessage message, CancellationToken cancellation) in E:\A\_work\403\s\src\Rpc\RpcSession.cs:line 702
 (7724836ms)
[2020-04-21 06:08:40.876 Command:l I] Decorator finishing: a. Duration: 4ms (0 + 4)
```

It is running VSOAgent_win_3658261 and I can confirm that I see a nullref exception while debugging 

More from the debug output:
```
Agent.Workspace Information: 0 : VSO - Invoking environment configuration.
Agent.Workspace Information: 0 : COMMAND: C:\Users\fpintos\.vsonline\cli\VSOAgent_win_3658261\vso.exe-d F:\ configure
Agent.Workspace Verbose: 0 : < #18 Microsoft.Cascade.Rpc.ResponseMessage
Agent.Rpc.Workspace Verbose: 0 : > #18 Microsoft.Cascade.Rpc.RequestMessage
Agent.Rpc.Workspace Verbose: 0 : < #14 Microsoft.Cascade.Rpc.NotificationMessage
Agent.Rpc.Workspace Verbose: 0 : < #15 Microsoft.Cascade.Rpc.NotificationMessage
Agent.Rpc.Workspace Verbose: 0 : < #16 Microsoft.Cascade.Rpc.NotificationMessage
Agent.Rpc.Workspace Verbose: 0 : < #17 Microsoft.Cascade.Rpc.NotificationMessage
Agent.Rpc.Workspace Verbose: 0 : < #18 Microsoft.Cascade.Rpc.ResponseMessage
Agent.Workspace Verbose: 0 : > #17 Microsoft.Cascade.Rpc.RequestMessage
Agent.Workspace Error: 0 : Exception in IVSCodeServerHostService.startRemoteServer request handler: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.LiveShare.Agent.VSCodeServerHost.VSCodeServerHostService.ReadDevContainer()
   at Microsoft.VisualStudio.LiveShare.Agent.VSCodeServerHost.VSCodeServerHostService.StartRemoteServerAsync(VSCodeServerOptions input, CancellationToken cancellationToken)
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.<>c__DisplayClass24_2.<<CreateDispatchMethod>b__4>d.MoveNext() in E:\A\_work\403\s\src\Rpc\RpcDispatcher.cs:line 311
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.HandleRequestAsync(RequestMessage request, IProgress`1 progress, CancellationToken cancellationToken) in E:\A\_work\403\s\src\Rpc\RpcDispatcher.cs:line 110
   at Microsoft.Cascade.Rpc.RpcSession.RequestAsync(IRpcService service, RequestMessage message, CancellationToken cancellation) in E:\A\_work\403\s\src\Rpc\RpcSession.cs:line 812
Agent.Workspace Verbose: 0 : < #17 Microsoft.Cascade.Rpc.ResponseMessage
Agent.Workspace Information: 0 : C:\Users\fpintos\.vsonline\cli\VSOAgent_win_3658261\vso.exe process exited with exit code 0
```

**Comment by taiyosogawa** [comment]
@fpintos, thanks for helping us out with these reports. I was able to repro the issue you posted when I had some old instances of the `vsls-agent` process running. The problem was resolved when I ran `vso stop` and made sure that all instances of `vsls-agent` and `vso` were terminated. Could you see if the same workaround works for you?

To make sure this scenario is better addressed, I have a few questions:
1) Were you running your environment as a process or a service?
2) What OS was the host machine running on?
3) When was your environment originally registered?

**Comment by fpintos** [comment]
@taiyosogawa , here are the steps I took trying to resolve this:
- hosting machine info from vscode:
Version: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19603

- environment were registered a while ago, before the option to run as process or service
- yesterday I unregistered all environments 
- played with vso start/stop
- killed all instances of vsls-agent
- deleted the agent folder to force vscode to download it again
- deleted the folder referenced by the debug log (the one in f:\.vsonline)
- re-registered, running as process

so far, the issue persists.

**Comment by crpytobi** [comment]
I'm having the exact same issue. Was fine 3 days ago, now I cannot get it working.

**Comment by taiyosogawa** [comment]
@fpintos, thanks for trying out and posting your troubleshooting steps and @crpytobi, thanks for posting. Are you running on Windows, too?

We're continuing to take a look into this.

**Comment by taiyosogawa** [comment]
We've identified the issue and are patching it up. In the meantime, the cli version of the self-hosted  https://docs.microsoft.com/en-us/visualstudio/online/how-to/self-hosting-cli should not be affected by this issue.

**Comment by crpytobi** [comment]
Yes, I'm on the current release of Windows 10. Thank you very much, I'll have a look into that option.

**Comment by CBlasek** [comment]
I am receiving this error as well and I am running the CLI version.

**Comment by taiyosogawa** [comment]
@crpytobi yes, you should be able to run via CMD (registering via VS Code will be affected).

@CBlasek, do you see what version of the CLI is running (should be printed when the command is run)? Where did you install it from?

**Comment by CBlasek** [comment]
@taiyosogawa 

This is running on windows server 2019 (1809)

VSS Online version: vso v1.0.2005.59801 

Installed using the powershell script located at https://vsoagentdownloads.blob.core.windows.net/vsoagent/installVSOAgent_win_3633968.ps1

**Comment by taiyosogawa** [comment]
@CBlasek, I'm sorry you're running into this issue. I wasn't able to repro with the CLI version you're using - I think it might be a different problem you're seeing. Are you seeing this same error in your host logs when you connect?

```
gent.Workspace Error: 0 : Exception in IVSCodeServerHostService.startRemoteServer request handler: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.LiveShare.Agent.VSCodeServerHost.VSCodeServerHostService.ReadDevContainer()
   at Microsoft.VisualStudio.LiveShare.Agent.VSCodeServerHost.VSCodeServerHostService.StartRemoteServerAsync(VSCodeServerOptions input, CancellationToken cancellationToken)
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.<>c__DisplayClass24_2.<<CreateDispatchMethod>b__4>d.MoveNext() in E:\A\_work\403\s\src\Rpc\RpcDispatcher.cs:line 311
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.HandleRequestAsync(RequestMessage request, IProgress`1 progress, CancellationToken cancellationToken) in E:\A\_work\403\s\src\Rpc\RpcDispatcher.cs:line 110
   at Microsoft.Cascade.Rpc.RpcSession.RequestAsync(IRpcService service, RequestMessage message, CancellationToken cancellation) in E:\A\_work\403\s\src\Rpc\RpcSession.cs:line 812
```

**Comment by taiyosogawa** [comment]
Thanks everyone for your patience. The fix for this has been rolled out. Please try:
1) make sure to kill any running instances of vsls-agent
2) try registering again (no extension update required)
