### ISSUE TITLE
self-registered instance on ubuntu failed with NOTICE.md missing error

### ISSUE THREAD

**Issue by OneCyrus** [MicrosoftDocs/vsonline#460]
today my self-registered instance on a ubuntu vm gave me the following error. I'm not aware that this file was ever there. i just noticed that the instance had a spinning icon in VS Code.

couldn't get it running again and stopped/started the install process.

```
[CLI E] Exception: System.IO.FileNotFoundException: Could not find file '/home/myuser/NOTICE.md'.
File name: '/home/myuser/NOTICE.md'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.CloudEnvironments.CLI.Commands.InfoCommandStrategy.<>c.<Register>b__1_1() in E:\A\_work\403\s\src\VSOnline\CLI\Commands\InfoCommandStrategy.cs:line 20
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.CloudEnvironments.CLI.Program.Main(String[] args) in E:\A\_work\403\s\src\VSOnline\CLI\Program.cs:line 148
```

**Comment by OneCyrus** [comment]
oh, just found this: https://github.com/MicrosoftDocs/vsonline/issues/407
