### ISSUE TITLE
Failed to Connect Remote Extension Host Server

### ISSUE THREAD

**Issue by Coding-Fusion** [MicrosoftDocs/vsonline#519]
****Self Hosted Code Space****

I have Mac OS, Installed VS Code already, Installed Azure Account Extension , Signed in

So once signed in Key chain added,
It fetched the Plan, 
Registered the instance, select local repo,

Once trying to connect from CodeSpace Online environment, it shows my remote codespace 
But once Visual Studio Opened, I can see below error under repos

**Error -Failed to start VS Code Remote Server**

**Comment by Coding-Fusion** [comment]
Can you look into the issues?

**Comment by taiyosogawa** [comment]
@Coding-Fusion, thanks for reporting this issue. We can start diagnosing with a couple things:

1) Can you verify that the agent is running on your Mac OS host. Run `ps aux | grep vsls-agent` and see if you see that a process is running.
2) Logs are output to `$TMPDIR/VSFeedbackVSRTCLogs` on the host machine. Try looking for any errors reported to this directory when you try to connect and let me know what you see.

**Comment by Coding-Fusion** [comment]
Hi Taiyo,

Here is the logs below

Debraths-MBP:mslearn-tailspin-spacegame-web debrathbanerjee$ ps aux | grep vsls-agent
debrathbanerjee  25083   0.0  0.4  6891648  67548   ??  S    Wed12AM   0:12.46 /Users/debrathbanerjee/.vsonline/cli/VSOAgent_osx_3720468/vsls-agent --pipe VSLS-SH-debrathbanerjee --service https://prod.liveshare.vsengsaas.visualstudio.com/api/v1.2/ --signalRServiceUri https://signlr-prod.core.vsengsaas.visualstudio.com/api/signalr/signalrhub --rpcFirstSessionTimeout 120000 --autoexit --verbosity All --agentExtensionPath /Users/debrathbanerjee/.vsonline/cli/VSOAgent_osx_3720468/AgentExtensions

debrathbanerjee  24782   0.0  0.2  6888320  40552   ??  S    Tue11PM   0:07.49 /Users/debrathbanerjee/.vsonline/cli/VSOAgent_osx_3720468/vsls-agent --pipe VSLS --service https://prod.liveshare.vsengsaas.visualstudio.com/api/v1.2/ --signalRServiceUri https://signlr-prod.core.vsengsaas.visualstudio.com/api/signalr/signalrhub --rpcFirstSessionTimeout 120000 --autoexit --verbosity All --agentExtensionPath /Users/debrathbanerjee/.vsonline/cli/VSOAgent_osx_3720468/AgentExtensions
debrathbanerjee  32125   0.0  0.0  4268340    744 s000  S+    8:22PM   0:00.00 grep vsls-agent
Debraths-MBP:mslearn-tailspin-spacegame-web debrathbanerjee$


Looks like its running.

From the logs , Also attached that.


[2020-05-20 05:32:17.901 Agent.Proxy I] No proxy information found.

[2020-05-20 05:32:18.510 Agent.Http E] > POST <https://prod.liveshare.vsengsaas.visualstudio.com/e7f052d6> (c609ms s<null>ms) => 404 Not Found

[2020-05-20 05:32:18.522 Agent-ObjectTracker V] Remove item:SharedWorkspace Id:5BB1F7DB3A2727AD5157F9399C121E4A6F4B count:1 others:[WorkspaceService currentWorkspaceId:5BB1F7DB3A2727AD5157F9399C121E4A6F4B]

[2020-05-20 05:32:18.525 Agent V] Listener stopped because the workspace was unshared.

[2020-05-20 05:32:18.534 Agent.Http V] < GET <https://prod.liveshare.vsengsaas.visualstudio.com/cec1ab18>

[2020-05-20 05:32:18.535 Agent.Proxy I] No proxy information found.

[2020-05-20 05:32:18.743 Agent.Http E] > GET <https://prod.liveshare.vsengsaas.visualstudio.com/cec1ab18> (c208ms s<null>ms) => 404 Not Found

[2020-05-20 05:32:18.754 Agent.Workspace I] UnshareWorkspace threw exception  System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.Cascade.Agent.WorkspaceService.UnshareWorkspaceAsync(String workspaceId, CancellationToken cancellationToken) in E:\A\_work\459\s\src\Agent\WorkspaceService.cs:line 617

   at Microsoft.Cascade.Agent.WorkspaceService.<>c__DisplayClass54_0.<<SetHeartbeatTimer>b__0>d.MoveNext() in E:\A\_work\459\s\src\Agent\WorkspaceService.cs:line 504

Thnx
Debrath

**Comment by Coding-Fusion** [comment]
Any findings Taiyo , why Codespace could not able to connect with local repo

Debrath

**Comment by Coding-Fusion** [comment]
[log.zip](https://github.com/MicrosoftDocs/vsonline/files/4669208/log.zip)

**Comment by Coding-Fusion** [comment]
Attached logfiles from  $TMPDIR/VSFeedbackVSRTCLogs

**Comment by taiyosogawa** [comment]
@Coding-Fusion, I looked through your logs. Although there are a few lines that look like errors, most were not applicable to this scenario and were non-impacting. I believe the server started correctly but failed to connect to Azure Relay:

```
[2020-05-20 04:57:18.875 Agent I] Relay listener connecting due to error: Microsoft.Azure.Relay.ConnectionLostException: InternalServerError: NameRenewalFailed
[2020-05-20 04:57:18.876 Agent.Proxy I] No proxy information found.
[2020-05-20 04:57:19.977 Agent I] Relay listener offline.
[2020-05-20 04:57:19.983 Agent I] Relay listener stopped.
[2020-05-20 04:57:19.986 Agent I] RelayRpcServer has lost connection. Unsharing workspace.
[2020-05-20 04:57:19.986 Agent.Workspace I] Server disconnected for relay.
[2020-05-20 05:32:17.900 Agent.Http V] < POST <https://prod.liveshare.vsengsaas.visualstudio.com/________>
[2020-05-20 05:32:17.901 Agent.Proxy I] No proxy information found.
[2020-05-20 05:32:18.510 Agent.Http E] > POST <https://prod.liveshare.vsengsaas.visualstudio.com/________> (c609ms s<null>ms) => 404 Not Found
```
@jasongin, have you seen this error before?

**Comment by Coding-Fusion** [comment]
No , I am first time trying configure that CodeSpace as per documentation, But not sure why its failing

I have attached full log file with the case too

Thanks
Debrath

**Comment by jasongin** [comment]
Sorry I don't know anything about that `NameRenewalFailed` error. Maybe the relay team will have more insight.

**Comment by taiyosogawa** [comment]
We have seen the same error message in some of our recent testing and have an update in our next extension release that might resolve this issue. I'll post when it is published.

**Comment by MaximeHeckel** [comment]
Got that same issue trying to connect to Codespaces on Github, looking forward to having the fix

**Comment by jkeech** [comment]
> Got that same issue trying to connect to Codespaces on Github, looking forward to having the fix

@MaximeHeckel, could you open a new issue with more details of what you are seeing in GitHub Codespaces so we can take a closer look? This issue is specific to self-hosted (which is not supported in GitHub yet). Thanks!
