### ISSUE TITLE
Fetching Plan doesn't work if behind a corporate proxy.

### ISSUE THREAD

**Issue by darktears** [MicrosoftDocs/vsonline#529]
Hi,

On Windows, I can't get the extension to fetch my configured plans if I'm behind my corp proxy. My proxy environment variables are set, the settings in Visual Studio code also set the proxy and everything is working just fine (extensions can connect, I can browse the market place, etc...).

However it fails over there when I try to select my plan (it may fail later, haven't been able to try after that):

```
[Client I] Extension activating {"isInternal":false,"isRunningInCloudEnvironment":false,"serviceEndpoint":"https://online.visualstudio.com/api/v1/environments"}
[EnvironmentDetailsExplorer I] Updating environment details
[Client I] Trace log: C:\Users\alexisme\AppData\Local\Temp/vsonline_logs/20200521_174659_15900832192860_VSCode.log
[Client I] User logged in as alexis-menard@outlook.com
[EnvironmentInfo E] Failed to fetch environments
Client network socket disconnected before secure TLS connection was established
  at connResetException (internal/errors.js:559:14)
  at TLSSocket.onConnectEnd (_tls_wrap.js:1357:19)
  at Object.onceWrapper (events.js:291:20)
  at TLSSocket.emit (events.js:208:15)
  at endReadableNT (_stream_readable.js:1168:12)
  at processTicksAndRejections (internal/process/task_queues.js:77:11)
[Command:l E] Command [Select Plan]: Select Plan Failure: Client network socket disconnected before secure TLS connection was established (70ms)
```

If I go to the terminal and try to curl that URL everything is working fine:

```bash
$curl https://online.visualstudio.com/api/v1/locations

{"current":"WestUs2","available":["EastUs","SouthEastAsia","WestEurope","WestUs2"],"hostnames":{"EastUs":"eastus.online.visualstudio.com","SouthEastAsia":"southeastasia.online.visualstudio.com","WestEurope":"westeurope.online.visualstudio.com","WestUs2":"westus2.online.visualstudio.com"}}
{"current":"WestUs2","available":["EastUs","SouthEastAsia","WestEurope","WestUs2"],"hostnames":{"EastUs":"eastus.online.visualstudio.com","SouthEastAsia":"southeastasia.online.visualstudio.com","WestEurope":"westeurope.online.visualstudio.com","WestUs2":"westus2.online.visualstudio.com"}}```
```

So it seems that the extension doesn't read the proxy settings or doesn't respect them.

Any idea?

**Comment by darktears** [comment]
It's reproducible on macOS as well. Same error.

**Comment by Bjego** [comment]
@darktears you can run a ntlm proxy fowarder like px. https://github.com/genotrance/px and set it as your proxy in VS Code
