### ISSUE TITLE
Unable to start VS Code and connect Code space

### ISSUE THREAD

**Issue by rroman81** [MicrosoftDocs/vsonline#533]
I recently created the Code Space and can connect to it via browser.  Then, i followed the  option to "open in VS code" which asked me to install the extension for "Remote Development".  
Upon finishing, i am attempting to connect to code space and getting this error in the log:
```
[Client V] Initializing authentication
[Client V] Initializing self-hosted environment registry
[Client I] Extension activating {"isInternal":false,"isRunningInCloudEnvironment":false,"serviceEndpoint":"https://online.visualstudio.com/api/v1/environments"}
[EnvironmentDetailsExplorer I] Updating environment details
[Client I] Trace log: C:\Users\rrozinov\AppData\Local\Temp/vsonline_logs/20200523_064038_15902160388020_VSCode.log
[EnvironmentDetailsExplorer I] Updating environment details
[EnvironmentInfo E] Failed to fetch environments
EnvironmentProvider found no cached tokens
Error: EnvironmentProvider found no cached tokens
    at t.VsoEnvironmentsApi.getTokenOrThrow (c:\Users\rrozinov\.vscode\extensions\ms-vsonline.vsonline-1.0.2220\src\partners\vso\vsoEnvironmentsApi.ts:321:19)
    at process.token (internal/process/task_queues.js:85:5)
    at t.VsoEnvironmentsApi.getActivePartnerContext [as getEnvironmentList] (c:\Users\rrozinov\.vscode\extensions\ms-vsonline.vsonline-1.0.2220\src\partners\vso\vsoEnvironmentsApi.ts:245:15)
    at p.updateEnvironmentsInfo (c:\Users\rrozinov\.vscode\extensions\ms-vsonline.vsonline-1.0.2220\src\EnvironmentInfo.ts:62:22)
[Command:g I] Decorator starting: l
[Command:g I] Decorator starting: a
[Connect I] Connecting to environment: {"isRunningInCloudEnvironment":false}
[Command:g E] Command [Connect to Codespace]: Connect to Codespace Failure:  (23ms)
[Command:g I] Decorator finishing: a. Duration: 15ms (2 + 13)
[Command:g I] Decorator finishing: l. Duration: 1ms (1 + 0)
```

**Comment by jkeech** [comment]
This looks similar to the error in #335, although based on the paths in the logs, it looks like this is happening on Windows. @legomushroom, @cmbrose can you help take a look at this?

@rroman81, can you try this potential workaround of removing the cached credentials? https://github.com/MicrosoftDocs/vsonline/issues/335#issuecomment-614949525. In Windows, the credentials are stored in the Credential Manager and prefixed with `VS Code`.

**Comment by rroman81** [comment]
i think that's the issue here with cached credentials.  When I re-login to Azure, i was able to see the codespace. So it's fixed.
