### ISSUE TITLE
vso script not able to start as service on RHEL7/CentOS7

### ISSUE THREAD

**Issue by xatier** [MicrosoftDocs/vsonline#600]
Hi,

I have the vso script installed with the following curl command on a RH7 box (ref: [1]).

```bash
curl -L https://aka.ms/install-vso-linux | sudo bash
```

When registering the host as self-hosted codespace environment (ref: [2]),

Running the `vso` script with the following would fail to create the codespace properly.

```bash
vso start --service
```

It seems like the `vso` script is attempting to invoke `systemd --user daemon-reload`

```text
Jun 19 04:38:06 rhel7 vso[27363]: Failed to run: systemctl {command}
Jun 19 04:38:06 rhel7 vso[27363]: CLI Error: 0 :
Jun 19 04:38:06 rhel7 vso[27363]: [!ERROR] Failed to register and start service/daemon: System.Exception: unable to run /bin/systemctl --user daemon-reload
                                                     at Microsoft.VisualStudio.VSOnline.Core.Platforms.Linux.LinuxDaemonManager.RunSystemCtl(String[] arguments) in E:\A\_work\510\s\src\VSOnline\Core\Platforms\Linux\LinuxDaemonManager.cs:line 197
                                                     at Microsoft.VisualStudio.VSOnline.Core.Platforms.Linux.LinuxDaemonManager.CreateServiceAsync(String user) in E:\A\_work\510\s\src\VSOnline\Core\Platforms\Linux\LinuxDaemonManager.cs:line 72
                                                     at Microsoft.CloudEnvironments.CLI.Commands.StartLocalEnvironmentCommand.StartVmAgentServiceAsync(String user) in E:\A\_work\510\s\src\VSOnline\CLI\Commands\StartLocalEnvironmentCommand.cs:line 207
                                                     at Microsoft.CloudEnvironments.CLI.Commands.StartLocalEnvironmentCommand.ExecuteAsync(RegisterEnvironmentParams parameters, String aadToken) in E:\A\_work\510\s\src\VSOnline\CLI\Commands\StartLocalEnvironmentCommand.cs:line 166
``` 

Sadly, `systemd --user` is not supported under RH7, or CentOS7 [3] [4].

The workaround is easy though, simply `vso start` without the `--service` flag and say `N` to `Would you like to run as a persistent service/daemon?`.

[1] https://docs.microsoft.com/en-us/visualstudio/online/reference/vsonline-cli
[2] https://docs.microsoft.com/en-us/visualstudio/online/how-to/self-hosting-cli#linux
[3] https://bugs.centos.org/view.php?id=8767
[4] https://bugzilla.redhat.com/show_bug.cgi?id=1173278

**Comment by xatier** [comment]
@nikmd23 :smile:

**Comment by ntziolis** [comment]
Same issue running on alpine linux which is the default distro (choosen by ms) when using remote container from vscode
