### ISSUE TITLE
Self hosted codespace not available once created

### ISSUE THREAD

**Issue by AlseinX** [MicrosoftDocs/vsonline#609]
+ OS: CentOS 8
+ Registered by vso cli with no error output and everything seems to be good
+ `https://online.visualstudio.com/environments` says my codespace is unavailable.
+ Openning the link given by the vso cli is infinitely initializing.
+ Tried unregistering and re-register but still unavailable.
+ `systemctl status --user vso` outputs:
```
● vso.service - VS Online Self-Hosted Service
   Loaded: loaded (/root/.config/systemd/user/vso.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-06-24 17:00:40 CST; 6min ago
 Main PID: 23509 (vso)
    Tasks: 17 (limit: 24004)
   Memory: 51.4M
   CGroup: /user.slice/user-0.slice/user@0.service/vso.service
           └─23509 /opt/vsonline/bin/vso vmagent -s -t

Jun 24 17:06:50 ovyno.com vso[23509]: Client.Rpc Information: 0 :
Jun 24 17:06:50 ovyno.com vso[23509]: RpcSession #26 is disposing.
Jun 24 17:06:50 ovyno.com vso[23509]: Client.Rpc Verbose: 0 :
Jun 24 17:06:50 ovyno.com vso[23509]: Emptying send queue of 0 messages.
Jun 24 17:06:50 ovyno.com vso[23509]: Client.Rpc Information: 0 :
Jun 24 17:06:50 ovyno.com vso[23509]: RpcSession #26 is disposing.
Jun 24 17:06:50 ovyno.com vso[23509]: CLI Information: 0 :
Jun 24 17:06:50 ovyno.com vso[23509]: {"Time":"2020-06-24T09:06:50.182819Z","Message":"selfhostedenvironmentmonitor_monitorasync-dead-env-found","Level":"info","OptionalValues":{"CorrelationId":"170b0129-68ad-4e4b-8a50-1010f65dfbcc","VsoAgentVersion":"1.0.2368.34261","ComputeResourceId":"516096df-5bfc-44e4-9e50-f5a1ebf36343","ComputeId":"516096df-5bfc-44e4-9e50-f5a1ebf36343","RunAsUser":"root","CloudEnvironmentId":"516096df-5bfc-44e4-9e50-f5a1ebf36343"}}
Jun 24 17:06:50 ovyno.com vso[23509]: Client.Rpc Verbose: 0 :
Jun 24 17:06:50 ovyno.com vso[23509]: <= ProcessMessagesInternalAsync session #:26
```

**Comment by AlseinX** [comment]
After `systemctl restart --user vso`
It says
```
Jun 24 17:28:25 ovyno.com vso[26065]: {"Time":"2020-06-24T09:28:25.637209Z","Message":"Failed to share environment","Level":"error","OptionalValues":{"Attempt":"2","ErrorException":"RemoteInvocationException","ErrorMessage":"Sequence contains more than one matching element","ErrorDetail":"[RemoteInvocationException]: Sequence contains more than one matching element\n--- Stack Trace ---\nMicrosoft.Cascade.Rpc.RemoteInvocationException: Sequence contains more than one matching element\n   at Microsoft.Cascade.Rpc.ResponseError.ThrowAsException() in E:\\A\\_work\\122\\s\\src\\Rpc\\Messages.cs:line 624\n   at Microsoft.Cascade.Rpc.RpcProxy.SendRequestAsync(RequestMessage request, CancellationToken cancellationToken, IProgress`1 progress) in E:\\A\\_work\\122\\s\\src\\Rpc\\RpcProxy.cs:line 242\n   at Microsoft.Cascade.Rpc.RpcProxy.InvokeAsync(String methodName, Object[] arguments, CancellationToken cancellationToken) in E:\\A\\_work\\122\\s\\src\\Rpc\\RpcProxy.cs:line 171\n   at Microsoft.VisualStudio.VSOnline.Core.Managers.WorkspaceManager.ShareAsync(ICascadeClient client, String path, Boolean allowAnonymousGuests, String workspaceId, UserAccountInfo userAccountInfo) in E:\\A\\_work\\122\\s\\src\\VSOnline\\Core\\Managers\\WorkspaceManager.cs:line 117\n   at Microsoft.VisualStudio.VSOnline.Core.Managers.WorkspaceManager.ShareAsync(String path, Boolean allowAnonymousGuests, String workspaceId, String pipeName, String serviceUri, UserAccountInfo userAccountInfo) in E:\\A\\_work\\122\\s\\src\\VSOnline\\Core\\Managers\\WorkspaceManager.cs:line 72\n   at Microsoft.CloudEnvironments.CLI.VmAgent.Monitoring.Monitors.SelfHostedEnvironmentMonitor.MonitorAsync(Action`2 OnMonitorDataReady, IDiagnosticsLogger logger) in E:\\A\\_work\\122\\s\\src\\VSOnline\\CLI\\VmAgent\\Monitoring\\Monitors\\SelfHostedEnvironmentMonitor.cs:line 82\n","CorrelationId":"2fc71332-b21a-4335-9379-cad1de54493c","VsoAgentVersion":"1.0.2368.34261","ComputeResourceId":"516096df-5bfc-44e4-9e50-f5a1ebf36343","ComputeId":"516096df-5bfc-44e4-9e50-f5a1ebf36343","RunAsUser":"root","CloudEnvironmentId":"516096df-5bfc-44e4-9e50-f5a1ebf36343"}}
Jun 24 17:28:25 ovyno.com vso[26065]: CLI Information: 0 :
Jun 24 17:28:25 ovyno.com vso[26065]: {"Time":"2020-06-24T09:28:25.637458Z","Message":"monitoringservice-onmonitordataready-environmentdata","Level":"info","OptionalValues":{"CorrelationId":"2fc71332-b21a-4335-9379-cad1de54493c","VsoAgentVersion":"1.0.2368.34261","ComputeResourceId":"516096df-5bfc-44e4-9e50-f5a1ebf36343","ComputeId":"516096df-5bfc-44e4-9e50-f5a1ebf36343","RunAsUser":"root","CloudEnvironmentId":"516096df-5bfc-44e4-9e50-f5a1ebf36343","CollectedData":"{\"state\":\"Unknown\",\"environmentType\":\"VirtualMachineBased\",\"timestamp\":\"2020-06-24T09:28:22.270804Z\",\"name\":\"EnvironmentData\",\"environmentId\":\"516096df-5bfc-44e4-9e50-f5a1ebf36343\"}"}}
Jun 24 17:28:25 ovyno.com vso[26065]: Client.Rpc Verbose: 0 :
Jun 24 17:28:25 ovyno.com vso[26065]: <= ProcessMessagesInternalAsync session #:4
Jun 24 17:28:26 ovyno.com vso[26065]: CLI Information: 0 :
Jun 24 17:28:26 ovyno.com vso[26065]: {"Time":"2020-06-24T09:28:26.150194Z","Message":"heartbeat_client_send_heartbeat_complete","Level":"info","OptionalValues":{"Duration":"00:00:00.4432590","CorrelationId":"14863576-e2f1-475c-8023-79d36b7002b3","VsoAgentVersion":"1.0.2368.34261","ComputeResourceId":"516096df-5bfc-44e4-9e50-f5a1ebf36343","ComputeId":"516096df-5bfc-44e4-9e50-f5a1ebf36343","CollectedData":"{\"timestamp\":\"2020-06-24T09:28:25.7066356Z\",\"agentVersion\":\"1.0.2368.34261\",\"resourceId\":\"516096df-5bfc-44e4-9e50-f5a1ebf36343\",\"environmentId\":\"516096df-5bfc-44e4-9e50-f5a1ebf36343\",\"collectedDataList\":[{\"state\":\"Unknown\",\"environmentType\":\"VirtualMachineBased\",\"timestamp\":\"2020-06-24T09:28:22.270804Z\",\"name\":\"EnvironmentData\",\"environmentId\":\"516096df-5bfc-44e4-9e50-f5a1ebf36343\"},{\"connectedSessionCount\":0,\"timestamp\":\"2020-06-24T09:28:25.7067292Z\",\"name\":\"EnvironmentSessionData\",\"environmentId\":\"516096df-5bfc-44e4-9e50-f5a1ebf36343\"},{\"hasChanges\":false,\"timestamp\":\"2020-06-24T09:28:25.7067311Z\",\"name\":\"GitChangesData\",\"environmentId\":\"516096df-5bfc-44e4-9e50-f5a1ebf36343\"}]}"}}
```

**Comment by OneCyrus** [comment]
i have the exact same issue since a couple of days here. also the same error after a restart.

**Comment by taiyosogawa** [comment]
This could be the same as #611 - we are looking into some issues following a cert rotation.

**Comment by damianmr** [comment]
I have the same error as the guys above, this was working fine a few days ago. Now, my codespace is always listed as "Unavailable" except for a few seconds immediately after I run `vso start`.

**Comment by asthomasdk** [comment]
I just set up a new Ubuntu 18.04 server running as the root user - and have the same problem. 

Initially I was able to get it to be available, then tried to connect, which failed - and now it is unavailable - even after reboots.

**Comment by damianmr** [comment]
Hi guys, does anyone know if this problem also happens when using an Azure hosted instance? Is this something that is affecting self-hosted spaces only?

**Comment by asthomasdk** [comment]
I have tried unregistering and registering again - making sure I had a non-root directory selected (`/opt/development`), cleaning up `/tmp` and rebooting in between. 

As soon as I try and connect to the codespace, it hangs on initializing and I can see the following messages repeated in logs (e.g. `20200702_160540_VSServerHost.log`) : 


```
[2020-07-02 16:05:16.269 VSServerHost I] Microsoft.VisualStudio.LiveShare.Agent.VSServerHost v1.0.1998.63218 (pid: 1737)
[2020-07-02 16:05:16.270 VSServerHost I] Multiple workspace feature not enabled. Creating instance of DummyVSServerHostService
```

No idea if this is good or bad ;-)

**Comment by OneCyrus** [comment]
any progress on this? i'm still unable to get this to work

**Comment by ckaczor** [comment]
For me on Ubuntu 18.04 Server this happens (working for a few seconds then going unavailable) if I try to run as a service.  If I just do "vso start" everything seems to be okay - I've had it working for a few days.

**Comment by rigobcastro** [comment]
Still happen here in Ubuntu 18.04 with vso `v1.0.1998.63218`

**Comment by MichalCz** [comment]
Likewise here - I'm trying to get this to work to test vso for a new project, but it seems to be failing for the same reason... I can share my plan info if needed.

**Comment by MichalCz** [comment]
Downgrading apt package to: `vso v1.0.1961.39102` works.

```sh
sudo apt install vso=1.0.1961
```

**Comment by MichalCz** [comment]
Nope. I take that back.

Seems that the self hosted codespaces simply **do not work at all**. 👎

**Comment by ckaczor** [comment]
I'm running v1.0.1998.63218 and it continues to work well as long as I don't run it as a service - I do just "vso start" and answer no when it asks if I want to run as a daemon.

**Comment by MichalCz** [comment]
I confirm - so daemonizing fails.

So a server restart means in essence a new env?

**Comment by ckaczor** [comment]
Not a whole new env but it seems to be like a new Codespace as far as the Azure side is concerned.  The few times I've had to reboot the server I've had to do:

- vso stop
- vso start
- Disconnect the old Codespace in vscode
- Connect to the new Codespace in vscode

All the code and everything is still there because the content on the server hasn't changed.  I can just pick right up wherever I left off without any new setup.  

It is a bit of a pain (especially since you need to do the "device logon" steps for each vso command) but I don't restart it very often so I can live with it for now.  =)

**Comment by damianmr** [comment]
I can confirm your suggestion @ckaczor, running as a daemon fails. The only way to run a self-hosted space is by running `vso start` (no daemon) on every boot. It's a bit of a pain to me as my remote server is paid by the hour, so I have to shut it down after I use it, but well at least I can have access to my env.

**Comment by damianmr** [comment]
Maybe it is useful to you guys @taiyosogawa & @jkeech  to label this issue as `area: self-hosting`? 

I want to kindly ask if it is on your plans fixing this since today I noticed that all references of `vso` were removed from the documentation site at https://docs.microsoft.com/en-us/visualstudio/codespaces/how-to/self-hosting-cli on this commit https://github.com/MicrosoftDocs/vscodespaces/commit/40c95cbaa5736e415060d6b5fbfe5c634c219187

At first, I thought the issue with the self-hosted envs would get fixed after installing `codespaces` since the version I get from `codespaces -info` is v1.0.2579.56687 (whereas the latest `vso -info` would return `v1.0.1998.63218` on Linux), but then I found that it's not possible to log in with my personal account, which is the one I was using when `vso` was working. 

This is the screen I see:
<img width="583" alt="Screen Shot 2020-08-06 at 21 53 51" src="https://user-images.githubusercontent.com/849343/89597024-52a79b80-d82f-11ea-94cb-334595b4cbed.png">

My account is a "pay as you go" Azure account.

So, all these changes made me realize that maybe there's a fundamental change in the business plans for VS CodeSpaces, which means that I wouldn't be able to host one as an individual in the future.

Is it possible for you to give us some updates? 

Thanks in advance!

**Comment by max06** [comment]
Having the exact same issue here: No login with Azure/Private Credentials, Self-hosted instance stays unavailable when started as a service...

**Comment by OneCyrus** [comment]
it looks like switching to the new codespaces cli fixes the issues for me. https://docs.microsoft.com/en-us/visualstudio/codespaces/reference/vsonline-cli#installation

**Comment by OneCyrus** [comment]
well, at least the service stays connected but there are still some connection issues on the client side. sometimes the local VSCode instance fails to connect but it works the 2nd or 3rd retry.


```
Failed to connect to the environment. Server responded with a non-101 status: 404 None of the connected listeners accepted the connection within the allowed timeout. TrackingId:ee6ec8eb-7b5f-4149-8fc7-9726ce1e1f40_G9, SystemTracker:sb://vsls-prod-ins-euw-private-relay.servicebus.windows.net/2a7a1b58f7c0ca836233fd0ba57481f7f082--ff43cd7a-a373-4020-879d-7774cb6c51fb, Timestamp:2020-08-07T12:59:35
Response Headers Follow:
transfer-encoding: chunked
server: Microsoft-HTTPAPI/2.0
trackingid: ee6ec8eb-7b5f-4149-8fc7-9726ce1e1f40_G9
date: Fri, 07 Aug 2020 12:59:35 GMT

Error: Failed to connect to the environment. Server responded with a non-101 status: 404 None of the connected listeners accepted the connection within the allowed timeout. TrackingId:ee6ec8eb-7b5f-4149-8fc7-9726ce1e1f40_G9, SystemTracker:sb://vsls-prod-ins-euw-private-relay.servicebus.windows.net/2a7a1b58f7c0ca836233fd0ba57481f7f082--ff43cd7a-a373-4020-879d-7774cb6c51fb, Timestamp:2020-08-07T12:59:35
Response Headers Follow:
transfer-encoding: chunked
server: Microsoft-HTTPAPI/2.0
trackingid: ee6ec8eb-7b5f-4149-8fc7-9726ce1e1f40_G9
date: Fri, 07 Aug 2020 12:59:35 GMT

    at failHandshake (c:\Users\giadgu\.vscode\extensions\node_modules\websocket\lib\WebSocketClient.js:339:32)
    at ClientRequest.<anonymous> (c:\Users\giadgu\.vscode\extensions\node_modules\websocket\lib\WebSocketClient.js:278:18)
    at ClientRequest.emit (events.js:208:15)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:575:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:449:22)
    at TLSSocket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at TLSSocket.Readable.push (_stream_readable.js:210:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by iamshital** [comment]
+1
