### ISSUE TITLE
self-hosted agent unable to validate token and instance is not flipping to 'available'.

### ISSUE THREAD

**Issue by definitelycarter** [MicrosoftDocs/vsonline#611]
I set up a linux machine around a month ago using the self-hosted cli option.  I noticed today that the agent is no longer connecting and becoming available in the Visual Studio Codespaces environment listing.  Poking around the logs and I see the token is failing validation.  Below is what I believe is the relevant section of the agent logs.

```
[2020-06-24 19:14:12.573 Agent I] Accepted incoming pipe connection.
[2020-06-24 19:14:12.573 Agent I] RPC session #6 established.
[2020-06-24 19:14:12.573 Agent-ObjectTracker V] Add item:RpcSession #6 count:2
[2020-06-24 19:14:12.573 Agent V] => ProcessMessagesInternalAsync session #:6
[2020-06-24 19:14:12.576 Agent V] > #6 {Id=1 Name=version.exchangeVersions}
[2020-06-24 19:14:12.576 Agent V] < #6 {Id=1}
[2020-06-24 19:14:12.577 Agent V] > #6 {Id=2 Name=version.exchangeSettings}
[2020-06-24 19:14:12.577 Agent V] < #6 {Id=2}
[2020-06-24 19:14:12.578 Agent.Rpc.Auth V] > #6 {Id=3 Name=auth.getCurrentUser}
[2020-06-24 19:14:12.578 Agent.Rpc.Auth V] < #6 {Id=3}
[2020-06-24 19:14:12.578 Agent.Rpc.Auth V] > #6 {Id=4 Name=auth.loginWithCachedToken}
[2020-06-24 19:14:12.578 Agent.Auth V] GetCredential(.vs-liveshare-keychain, <19:8d872bcf>)
[2020-06-24 19:14:12.578 Agent.Auth V] GetCredential(.vs-liveshare-keychain, <19:b456cd92>)
[2020-06-24 19:14:12.578 Agent.Auth V] GetCredential(.vs-liveshare-keychain, <28:adfd9403>)
[2020-06-24 19:14:12.578 Agent.Auth I] isValidExpirationTime=False (6/24/2020 4:38:46 PM - 6/25/2020 7:14:12 PM)
[2020-06-24 19:14:12.578 Agent.Auth I] isValidIssuedAtTime=True (5/31/2020 4:38:46 PM - 24)
[2020-06-24 19:14:12.578 Agent.Auth I] isValidAudience=True (https://insiders.liveshare.vsengsaas.visualstudio.com/api/v1.2/ - https://insiders.liveshare.vsengsaas.visualstudio.com/)
[2020-06-24 19:14:12.578 Agent.Auth W] Failed token validation
[2020-06-24 19:14:12.579 Agent.Auth I] Logging out...
[2020-06-24 19:14:12.579 Agent.Rpc.Auth V] < #6 {Name=auth.authenticationChanged}
[2020-06-24 19:14:12.579 Agent.Auth I] Logged out.
[2020-06-24 19:14:12.579 Agent.Rpc.Auth V] < #6 {Id=4}
[2020-06-24 19:14:12.579 Agent.Rpc.Auth V] > #6 {Id=5 Name=auth.getLoginUri}
[2020-06-24 19:14:12.579 Agent.Rpc.Auth V] < #6 {Id=5}
[2020-06-24 19:14:12.579 Agent.Rpc.Auth V] > #6 {Id=6 Name=auth.findLoginCode}
[2020-06-24 19:14:12.581 Agent.Rpc.Auth E] Exception in auth.findLoginCode request handler: System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.Cascade.Platforms.PlatformServices.<>c.<.cctor>b__23_6() in E:\A\_work\459\s\src\Agent\Platforms\PlatformServices.cs:line 78
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.Cascade.Agent.AuthenticationService.FindLoginCodeAsync(String extensionId, CancellationToken cancellationToken) in E:\A\_work\459\s\src\Agent\AuthenticationService.cs:line 97
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.<>c__DisplayClass24_2.<<CreateDispatchMethod>b__4>d.MoveNext() in E:\A\_work\459\s\src\Rpc\RpcDispatcher.cs:line 310
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.HandleRequestAsync(RequestMessage request, IProgress`1 progress, CancellationToken cancellationToken) in E:\A\_work\459\s\src\Rpc\RpcDispatcher.cs:line 102
   at Microsoft.Cascade.Rpc.RpcSession.RequestAsync(IRpcService service, RequestMessage message, CancellationToken cancellation) in E:\A\_work\459\s\src\Rpc\RpcSession.cs:line 702
[2020-06-24 19:14:12.581 Agent.Rpc.Auth V] < #6 {Id=6 Error={Code=-32098 Message=The method or operation is not implemented. Data=(StackTrace=System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.Cascade.Platforms.PlatformServices.<>c.<.cctor>b__23_6() in E:\A\_work\459\s\src\Agent\Platforms\PlatformServices.cs:line 78
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.Cascade.Agent.AuthenticationService.FindLoginCodeAsync(String extensionId, CancellationToken cancellationToken) in E:\A\_work\459\s\src\Agent\AuthenticationService.cs:line 97
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.<>c__DisplayClass24_2.<<CreateDispatchMethod>b__4>d.MoveNext() in E:\A\_work\459\s\src\Rpc\RpcDispatcher.cs:line 310
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.HandleRequestAsync(RequestMessage request, IProgress`1 progress, CancellationToken cancellationToken) in E:\A\_work\459\s\src\Rpc\RpcDispatcher.cs:line 102
   at Microsoft.Cascade.Rpc.RpcSession.RequestAsync(IRpcService service, RequestMessage message, CancellationToken cancellation) in E:\A\_work\459\s\src\Rpc\RpcSession.cs:line 702)}}
[2020-06-24 19:14:12.582 Agent I] #6 Disconnected: Reached end of stream.
[2020-06-24 19:14:12.582 Agent I] RPC session #6 disconnected: Reached end of stream.
[2020-06-24 19:14:12.582 Agent V] Emptying send queue of 0 messages.
[2020-06-24 19:14:12.582 Agent I] RpcSession #6 is disposing.
[2020-06-24 19:14:12.582 Agent-ObjectTracker V] Remove item:RpcSession #6 count:1 others:[KeepAliveAgent reason:AgentStarted delay:120000]
```

**Comment by definitelycarter** [comment]
I am trying to re-register my instance with the latest version of `vso` (appears to be 1.0.2368) and I am seeing logs stating my token has expired with a 401.

```
[2020-06-24 20:17:56.252 Agent.Rpc.Workspace V] > #15 {Id=3 Name=workspace.listWorkspaces}
[2020-06-24 20:17:56.252 Agent.Rpc.Workspace V] < #15 {Id=3}
[2020-06-24 20:17:56.253 Agent.Rpc.Workspace V] > #15 {Id=4 Name=workspace.getInvitationLinks}
[2020-06-24 20:17:56.253 Agent.Http V] < GET <https://prod.liveshare.vsengsaas.visualstudio.com/0f24f418>
[2020-06-24 20:17:56.298 Agent.Http E] > GET <https://prod.liveshare.vsengsaas.visualstudio.com/0f24f418> (c44ms s<null>ms) => 401 Unauthorized
[2020-06-24 20:17:56.300 Agent.Rpc.Workspace E] Remote exception in workspace.getInvitationLinks request handler: Microsoft.Cascade.Agent.HttpResponseStatusException: Your sign in token has expired. Please sign out and in again to refresh it. If the issue persists, please log a bug.
   at Microsoft.Cascade.Agent.HttpResponseMessageExtensions.ThrowHttpStatusException(HttpResponseMessage response) in E:\A\_work\122\s\src\Agent\HttpResponseMessageExtensions.cs:line 90
   at Microsoft.Cascade.Agent.HttpResponseMessageExtensions.ThrowIfFailedAsync(HttpResponseMessage response) in E:\A\_work\122\s\src\Agent\HttpResponseMessageExtensions.cs:line 46
   at Microsoft.Cascade.Agent.WebApiCollection`1.ReadAsync(String id, CancellationToken cancellationToken) in E:\A\_work\122\s\src\Agent\WebApiCollection.cs:line 74
   at Microsoft.Cascade.Agent.WorkspaceService.GetInvitationLinksAsync(String workspaceId, CancellationToken cancellationToken) in E:\A\_work\122\s\src\Agent\WorkspaceService.cs:line 1271
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.<>c__DisplayClass24_2.<<CreateDispatchMethod>b__4>d.MoveNext() in E:\A\_work\122\s\src\Rpc\RpcDispatcher.cs:line 311
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.HandleRequestAsync(RequestMessage request, IProgress`1 progress, CancellationToken cancellationToken) in E:\A\_work\122\s\src\Rpc\RpcDispatcher.cs:line 110
   at Microsoft.Cascade.Rpc.RpcSession.RequestAsync(IRpcService service, RequestMessage message, CancellationToken cancellation) in E:\A\_work\122\s\src\Rpc\RpcSession.cs:line 812
[2020-06-24 20:17:56.302 Agent.Rpc.Workspace V] < #15 {Id=4 Error={Code=-32032 Message=Your sign in token has expired. Please sign out and in again to refresh it. If the issue persists, please log a bug. Data=(StackTrace=   at Microsoft.Cascade.Agent.HttpResponseMessageExtensions.ThrowHttpStatusException(HttpResponseMessage response) in E:\A\_work\122\s\src\Agent\HttpResponseMessageExtensions.cs:line 90
   at Microsoft.Cascade.Agent.HttpResponseMessageExtensions.ThrowIfFailedAsync(HttpResponseMessage response) in E:\A\_work\122\s\src\Agent\HttpResponseMessageExtensions.cs:line 46
   at Microsoft.Cascade.Agent.WebApiCollection`1.ReadAsync(String id, CancellationToken cancellationToken) in E:\A\_work\122\s\src\Agent\WebApiCollection.cs:line 74
   at Microsoft.Cascade.Agent.WorkspaceService.GetInvitationLinksAsync(String workspaceId, CancellationToken cancellationToken) in E:\A\_work\122\s\src\Agent\WorkspaceService.cs:line 1271
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.<>c__DisplayClass24_2.<<CreateDispatchMethod>b__4>d.MoveNext() in E:\A\_work\122\s\src\Rpc\RpcDispatcher.cs:line 311
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.HandleRequestAsync(RequestMessage request, IProgress`1 progress, CancellationToken cancellationToken) in E:\A\_work\122\s\src\Rpc\RpcDispatcher.cs:line 110
   at Microsoft.Cascade.Rpc.RpcSession.RequestAsync(IRpcService service, RequestMessage message, CancellationToken cancellation) in E:\A\_work\122\s\src\Rpc\RpcSession.cs:line 812, StatusCode=401)}}
[2020-06-24 20:17:56.304 Agent.Rpc.Workspace V] > #15 {Id=5 Name=workspace.getInvitationLinks}
[2020-06-24 20:17:56.304 Agent.Http V] < GET <https://prod.liveshare.vsengsaas.visualstudio.com/0f24f418>
[2020-06-24 20:17:56.345 Agent.Http E] > GET <https://prod.liveshare.vsengsaas.visualstudio.com/0f24f418> (c40ms s<null>ms) => 401 Unauthorized
[2020-06-24 20:17:56.346 Agent.Rpc.Workspace E] Remote exception in workspace.getInvitationLinks request handler: Microsoft.Cascade.Agent.HttpResponseStatusException: Your sign in token has expired. Please sign out and in again to refresh it. If the issue persists, please log a bug.
   at Microsoft.Cascade.Agent.HttpResponseMessageExtensions.ThrowHttpStatusException(HttpResponseMessage response) in E:\A\_work\122\s\src\Agent\HttpResponseMessageExtensions.cs:line 90
   at Microsoft.Cascade.Agent.HttpResponseMessageExtensions.ThrowIfFailedAsync(HttpResponseMessage response) in E:\A\_work\122\s\src\Agent\HttpResponseMessageExtensions.cs:line 46
   at Microsoft.Cascade.Agent.WebApiCollection`1.ReadAsync(String id, CancellationToken cancellationToken) in E:\A\_work\122\s\src\Agent\WebApiCollection.cs:line 74
   at Microsoft.Cascade.Agent.WorkspaceService.GetInvitationLinksAsync(String workspaceId, CancellationToken cancellationToken) in E:\A\_work\122\s\src\Agent\WorkspaceService.cs:line 1271
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.<>c__DisplayClass24_2.<<CreateDispatchMethod>b__4>d.MoveNext() in E:\A\_work\122\s\src\Rpc\RpcDispatcher.cs:line 311
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.HandleRequestAsync(RequestMessage request, IProgress`1 progress, CancellationToken cancellationToken) in E:\A\_work\122\s\src\Rpc\RpcDispatcher.cs:line 110
   at Microsoft.Cascade.Rpc.RpcSession.RequestAsync(IRpcService service, RequestMessage message, CancellationToken cancellation) in E:\A\_work\122\s\src\Rpc\RpcSession.cs:line 812
[2020-06-24 20:17:56.347 Agent.Rpc.Workspace V] < #15 {Id=5 Error={Code=-32032 Message=Your sign in token has expired. Please sign out and in again to refresh it. If the issue persists, please log a bug. Data=(StackTrace=   at Microsoft.Cascade.Agent.HttpResponseMessageExtensions.ThrowHttpStatusException(HttpResponseMessage response) in E:\A\_work\122\s\src\Agent\HttpResponseMessageExtensions.cs:line 90
   at Microsoft.Cascade.Agent.HttpResponseMessageExtensions.ThrowIfFailedAsync(HttpResponseMessage response) in E:\A\_work\122\s\src\Agent\HttpResponseMessageExtensions.cs:line 46
   at Microsoft.Cascade.Agent.WebApiCollection`1.ReadAsync(String id, CancellationToken cancellationToken) in E:\A\_work\122\s\src\Agent\WebApiCollection.cs:line 74
   at Microsoft.Cascade.Agent.WorkspaceService.GetInvitationLinksAsync(String workspaceId, CancellationToken cancellationToken) in E:\A\_work\122\s\src\Agent\WorkspaceService.cs:line 1271
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.<>c__DisplayClass24_2.<<CreateDispatchMethod>b__4>d.MoveNext() in E:\A\_work\122\s\src\Rpc\RpcDispatcher.cs:line 311
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.HandleRequestAsync(RequestMessage request, IProgress`1 progress, CancellationToken cancellationToken) in E:\A\_work\122\s\src\Rpc\RpcDispatcher.cs:line 110
   at Microsoft.Cascade.Rpc.RpcSession.RequestAsync(IRpcService service, RequestMessage message, CancellationToken cancellation) in E:\A\_work\122\s\src\Rpc\RpcSession.cs:line 812, StatusCode=401)}}
[2020-06-24 20:17:56.348 Agent.Rpc.Workspace V] > #15 {Id=6 Name=workspace.getInvitationLinks}
[2020-06-24 20:17:56.348 Agent.Http V] < GET <https://prod.liveshare.vsengsaas.visualstudio.com/0f24f418>
[2020-06-24 20:17:56.402 Agent.Http E] > GET <https://prod.liveshare.vsengsaas.visualstudio.com/0f24f418> (c53ms s<null>ms) => 401 Unauthorized
```

**Comment by taiyosogawa** [comment]
Hi @definitelycarter, thanks for reporting this and finding the relevant information in your logs. Could you try deleting your `~/.vs-liveshare-keychain` file and registering again?

**Comment by definitelycarter** [comment]
Hi @taiyosogawa - I deleted the following files and I am getting the same response:

- ~/.vsonline/selfHosted.json
- ~/.vs-liveshare-keychain
- ~/.vs-liveshare-settings.json

**Comment by taiyosogawa** [comment]
Thanks! Love the callouts in the screenshot. We're taking a look into it.

**Comment by taiyosogawa** [comment]
Still working on this - will post when some updates have been released.

**Comment by damianmr** [comment]
Hi @taiyosogawa, is there any news on this? Is there any debugging information we could add to help you on this matter?

**Comment by taiyosogawa** [comment]
Sorry for the delay - I just pinged the people who are investigating this for an update.

**Comment by BradBarnich** [comment]
I see the same issue when using a windows host, running as a service. running as a process works fine 🤷‍♂️

**Comment by mlacouture** [comment]
looping @jramsay who has been investigating token expiration and signing issues.
